# Generated by Django 4.2.1 on 2023-07-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='hero_img/'),
        ),
    ]
