# Generated by Django 4.2.1 on 2023-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_heroes_hero_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_characters',
            name='side_img',
            field=models.ImageField(blank=True, upload_to='side_img/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='villains',
            name='vl_img',
            field=models.ImageField(blank=True, upload_to='vl_img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='bio',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='hero_img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='male',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='powers',
            field=models.TextField(verbose_name='Способности'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='real_name',
            field=models.CharField(max_length=50, verbose_name='Реальное имя'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='short_info',
            field=models.TextField(verbose_name='Красткая сводка'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='superhero_name',
            field=models.CharField(max_length=100, verbose_name='Супергеройское имя'),
        ),
        migrations.AlterField(
            model_name='side_characters',
            name='attitude',
            field=models.CharField(max_length=100, verbose_name='Отношение'),
        ),
        migrations.AlterField(
            model_name='side_characters',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='side_characters',
            name='info',
            field=models.TextField(verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='side_characters',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='bio',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='male',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='powers',
            field=models.TextField(verbose_name='Способности'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='real_name',
            field=models.CharField(max_length=50, verbose_name='Реальное имя'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='short_info',
            field=models.TextField(verbose_name='Краткая сводка'),
        ),
        migrations.AlterField(
            model_name='villains',
            name='villiain_name',
            field=models.CharField(max_length=100, verbose_name='Злодейский псевдоним'),
        ),
    ]
