# Generated by Django 4.2.1 on 2023-07-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_film_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_img',
            field=models.ImageField(blank=True, upload_to='movie_img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='plot',
            field=models.TextField(verbose_name='Сюжет'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
